### ISSUE TITLE
Deflater in PngEncoder is never released

### ISSUE THREAD

**Issue by mogamusa31** [oupson/Kapng-Android#6] opened 2020-04-20 05:46 UTC
Hello

I am using Kapng-Android to output Apng with an Android application.
Thank you very much.

Regarding Issue of the main subject, I received the following warning called LeakedClosableViolation in the process of adding Frame of Apng. Checking the warning explains that the Deflater instance in PngEncoder is not released. Is there anything you know about this?

I don't know if this is directly related, but OutBytes in PngEncoder was not closed. This issue has not been warned, but I feel like I'm likely to receive a warning from LeakedClosableViolation as well. Therefore, if you haven't closed it unintentionally, I would like you to add a modification to close it.

Thank you for your response.

``` error detail
D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1803)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:264)
        at java.util.zip.Deflater.finalize(Deflater.java:567)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.Throwable: Explicit termination method 'end' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:221)
        at java.util.zip.Deflater.<init>(Deflater.java:181)
        at java.util.zip.Deflater.<init>(Deflater.java:190)
        at oupson.apng.imageUtils.PngEncoder$Companion.writeImageData(PngEncoder.kt:314)
        at oupson.apng.imageUtils.PngEncoder$Companion.encode(PngEncoder.kt:113)
        at oupson.apng.imageUtils.PngEncoder$Companion.encode$default(PngEncoder.kt:82)
        at oupson.apng.Apng.addFrames(Apng.kt:52)
        at oupson.apng.Apng.addFrames$default(Apng.kt:50)
```

**Comment by mogamusa31** [comment] 2020-04-20 06:05
I think this problem can be solved by calling scruch.end () after scruch.finish (), but how about that?

https://github.com/oupson/Kapng-Android/blob/master/apng_library/src/main/java/oupson/apng/imageUtils/PngEncoder.kt#L391

**Comment by oupson** [comment] 2020-04-20 09:40
Hi, I added scruch.end() as you ask me. I never encountered this issue before, thank you for your bug report. I hope the issue is fixed.

**Comment by mogamusa31** [comment] 2020-04-21 01:07
Thank you for your reply.
And thank you for your prompt response.

When using the modified version, the warning of LeakedClosableViolation disappeared, and it was confirmed that it was operating normally.

This time, thank you very much.

**Comment by oupson** [comment] 2020-04-21 11:31
If everything work, I close the issue. Thank you for your report.

**Closed by oupson** 2020-04-21 11:31 UTC
